import { CameraRuntime } from './camera-runtime.js';
import { mapCover } from './geometry.mjs';
import { storeRemote, currentRemote } from './remote-state.mjs';
import './qr-init.js';
const $=id=>document.getElementById(id);
const state={mode:'sim',running:false,samples:[],runtime:null,remote:{A:null,B:null}};
const edges=[[11,12],[23,24],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,25],[25,27],[24,26],[26,28]];
const mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2,visibility:Math.min(a.visibility??1,b.visibility??1)});
const axis=l=>{const s=mid(l[11],l[12]),h=mid(l[23],l[24]);return Math.atan2(h.x-s.x,h.y-s.y)*180/Math.PI};
const joint=(a,b,c)=>Math.acos(Math.max(-1,Math.min(1,((a.x-b.x)*(c.x-b.x)+(a.y-b.y)*(c.y-b.y))/(Math.hypot(a.x-b.x,a.y-b.y)*Math.hypot(c.x-b.x,c.y-b.y)||1))))*180/Math.PI;
const message=t=>{if($('notice'))$('notice').textContent=t};
function draw(id,l,meta={}){const c=$(id),g=c?.getContext('2d'),v=$(id==='canvasA'?'videoA':'videoB');if(!c||!g)return;c.width=Math.max(1,c.clientWidth*devicePixelRatio);c.height=Math.max(1,c.clientHeight*devicePixelRatio);g.clearRect(0,0,c.width,c.height);if(!l)return;const mirror=!!meta.mirror;const point=p=>mapCover(p,meta.videoWidth||v?.videoWidth||c.width,meta.videoHeight||v?.videoHeight||c.height,c.width,c.height,mirror);if($('showSkeleton')?.checked){g.strokeStyle='#59d6c7';g.lineWidth=Math.max(1,devicePixelRatio*2);for(const[a,b]of edges){if(!l[a]||!l[b]||(l[a].visibility??1)<.45||(l[b].visibility??1)<.45)continue;const p=point(l[a]),q=point(l[b]);g.beginPath();g.moveTo(p.x,p.y);g.lineTo(q.x,q.y);g.stroke()}}if($('showAxis')?.checked){const s=point(mid(l[11],l[12])),h=point(mid(l[23],l[24]));g.strokeStyle='#f3c969';g.lineWidth=Math.max(1,devicePixelRatio*2);g.beginPath();g.moveTo(c.width/2,0);g.lineTo(c.width/2,c.height);g.stroke();g.strokeStyle='#59d6c7';g.beginPath();g.moveTo(s.x,s.y);g.lineTo(h.x,h.y);g.stroke()}}
function synth(t){const l=Array.from({length:33},()=>({x:.5,y:.5,visibility:.98})),q=Math.sin(t*3.4)*.06,arm=Math.sin(t*3)*.08;l[11]={x:.43+q,y:.25,visibility:.98};l[12]={x:.57+q,y:.25,visibility:.98};l[23]={x:.46+q,y:.54,visibility:.97};l[24]={x:.54+q,y:.54,visibility:.97};l[13]={x:.38+arm,y:.31,visibility:.96};l[14]={x:.62-arm,y:.31,visibility:.96};l[15]={x:.34+arm,y:.35,visibility:.96};l[16]={x:.66-arm,y:.35,visibility:.96};l[25]={x:.45+q,y:.76,visibility:.96};l[26]={x:.55+q,y:.76,visibility:.96};l[27]={x:.43+q,y:.94,visibility:.95};l[28]={x:.57+q,y:.94,visibility:.95};return l}
function current(id){if(state.mode==='sim')return {landmarks:synth(performance.now()/1000),meta:{}};const remote=currentRemote(state.remote,id,performance.now());if(remote)return remote;return {landmarks:state.runtime?.landmarks?.[id]||null,meta:{}}}
function frame(t){if(!state.running)return;const a=current('A'),b=current('B'),al=a.landmarks,bl=b.landmarks;draw('canvasA',al,a.meta);draw('canvasB',bl,b.meta);const av=al?axis(al):null,k=bl?joint(bl[23],bl[25],bl[27]):null;state.samples.push({timestamp:t,view:'front',axis:av,knee:k,leftHand:al?.[15]?.y??null,rightHand:al?.[16]?.y??null,confidence:al?.[11]?.visibility??null,bConfidence:bl?.[11]?.visibility??null,missing:!al||!bl});if(state.samples.length>300)state.samples.shift();if($('trunkValue'))$('trunkValue').textContent=av==null?'—':av.toFixed(1)+'°';if($('kneeValue'))$('kneeValue').textContent=k==null?'—':k.toFixed(1)+'°';if($('confValue'))$('confValue').textContent=`${(al?.[11]?.visibility??0).toFixed(2)} / ${(bl?.[11]?.visibility??0).toFixed(2)}`;requestAnimationFrame(frame)}
function startSim(){stop();state.mode='sim';state.running=true;$('aState').textContent='模擬';$('bState').textContent='模擬';message('模擬データを開始しました（実測値ではありません）');requestAnimationFrame(frame)}
async function startCams(){stop();state.mode='camera';state.runtime=new CameraRuntime({onState:(id,text)=>{const e=$(id==='A'?'aState':'bState');if(e)e.textContent=text},onError:message,onFrame:(id,lm)=>{if(!lm)draw(id==='A'?'canvasA':'canvasB',null)}});if(await state.runtime.start()){state.running=true;requestAnimationFrame(frame)}else message('カメラ開始を中止しました')}
function stop(){state.running=false;state.remote={A:null,B:null};state.runtime?.stop();state.runtime=null;for(const id of['A','B']){$(id==='A'?'aState':'bState').textContent='停止';draw(id==='A'?'canvasA':'canvasB',null)}}
function download(kind){const data=kind==='json'?JSON.stringify({mode:state.mode,samples:state.samples},null,2):'timestamp,view,axis,knee,leftHand,rightHand,confidence,bConfidence,missing\n'+state.samples.map(s=>Object.values(s).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:kind==='json'?'application/json':'text/csv'}));a.download='slackline-bf.'+kind;a.click()}
for(const id of['startSim','startCams','stopAll','downloadCsv','downloadJson','fullscreen'])$(id)?.addEventListener('click',id==='startSim'?startSim:id==='startCams'?startCams:id==='stopAll'?stop:id==='downloadCsv'?()=>download('csv'):id==='downloadJson'?()=>download('json'):()=>document.documentElement.requestFullscreen?.());
for(const id of['showVideo','showSkeleton','showAxis'])$(id)?.addEventListener('change',()=>{if(id==='showVideo')document.querySelectorAll('video').forEach(v=>v.style.visibility=$(id).checked?'visible':'hidden')});
window.addEventListener('error',e=>message('JavaScriptエラー: '+e.message));window.addEventListener('unhandledrejection',e=>message('非同期エラー: '+e.reason));
async function setupRemote(){try{const{default:Peer}=await import('https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm');const peer=new Peer();peer.on('open',id=>{if($('roomCode'))$('roomCode').textContent=`ROOM ${id.slice(-6).toUpperCase()}`;for(const slot of['A','B']){const u=new URL('./capture.html',location.href);u.searchParams.set('peer',id);u.searchParams.set('source',slot);const link=$('link'+slot);if(link)link.href=u.href;const qr=$('qr'+slot);if(window.QRCode&&qr){qr.replaceChildren();new QRCode(qr,{text:u.href,width:160,height:160})}}});peer.on('call',call=>{const slot=call.metadata?.source==='B'?'B':'A';call.answer(new MediaStream());call.on('stream',s=>{const v=$('video'+slot);if(v){v.srcObject=s;v.play().catch(()=>{})}$('state'+slot).textContent='スマホ接続済み・映像受信中'});call.on('close',()=>{$('state'+slot).textContent='接続切断'})});peer.on('connection',conn=>{const slot=conn.metadata?.source==='B'?'B':'A';conn.on('data',d=>{if(d.type!=='pose')return;state.remote[slot]={landmarks:d.landmarks,receivedAt:performance.now(),timestamp:d.timestamp,meta:{videoWidth:d.videoWidth,videoHeight:d.videoHeight,mirror:d.mirror}};const e=$('state'+slot);if(e)e.textContent=d.landmarks?.length===33?'ランドマーク受信中: 33点':'映像あり・人物未検出'});conn.on('close',()=>{$('state'+slot).textContent='ランドマーク受信停止'})})}catch(e){message('PeerJS接続失敗: '+e.message)}}
setupRemote();
setInterval(()=>{if(!state.running&&Object.values(state.remote).some(Boolean)){state.mode='camera';state.running=true;requestAnimationFrame(frame)}},200);
