import { CameraRuntime } from './camera-runtime.js';
import { mapCover } from './geometry.mjs';
import { storeRemote, currentRemote } from './remote-state.mjs';
import { measurePose } from './measurements.mjs';
import { circularMeanDegrees, relativePhase, wrapDegrees } from './phase.mjs';
import { drawPhaseChart, renderPhaseGauge } from './phase-view.mjs';
import { appendPhaseHistory, appendTrialSample, beginTrial, createTrialState, endTrial, resetTrialState } from './trial-state.mjs';
import './qr-init.js';
const $=id=>document.getElementById(id), nowIso=()=>new Date().toISOString();
const sessionId=crypto.randomUUID();
const state={mode:'idle',looping:false,trial:createTrialState(),phaseWindow:[],runtime:null,remote:{A:null,B:null},connections:{},previous:{A:null,B:null},terminalPhase:null};
const edges=[[11,12],[23,24],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,25],[25,27],[24,26],[26,28]];
const settings=()=>({when:$('when').value,what:$('what').value,amount:$('amount').value,how:$('how').value,variables:[...document.querySelectorAll('#variables input:checked')].map(x=>x.value),side:$('side').value,target:Number($('target').value),tolerance:Number($('tolerance').value),sourceA:$('sourceA').value,sourceB:$('sourceB').value,cameraAEnabled:$('cameraAEnabled').checked,cameraBEnabled:$('cameraBEnabled').checked,liveVideo:$('liveVideo').value});
const message=t=>$('notice').textContent=t;
const midpoint=(a,b)=>a&&b?{x:(a.x+b.x)/2,y:(a.y+b.y)/2}:null;
function draw(id,l,meta={}){const c=$('canvas'+id),g=c.getContext('2d'),v=$('video'+id),d=devicePixelRatio;c.width=Math.max(1,c.clientWidth*d);c.height=Math.max(1,c.clientHeight*d);g.clearRect(0,0,c.width,c.height);if(!l)return;const p=x=>mapCover(x,meta.videoWidth||v.videoWidth||c.width,meta.videoHeight||v.videoHeight||c.height,c.width,c.height,!!meta.mirror);const style=settings().how;if(style==='skeleton'){g.strokeStyle='#59d6c7';g.lineWidth=2*d;for(const[a,b]of edges){if((l[a]?.visibility??0)<.5||(l[b]?.visibility??0)<.5)continue;const x=p(l[a]),y=p(l[b]);g.beginPath();g.moveTo(x.x,x.y);g.lineTo(y.x,y.y);g.stroke()}}const s=midpoint(l[11],l[12]),h=midpoint(l[23],l[24]);if(s&&h){g.lineWidth=2*d;g.strokeStyle='#f3c969';g.beginPath();g.moveTo(c.width/2,0);g.lineTo(c.width/2,c.height);g.stroke();g.strokeStyle='#59d6c7';const x=p(s),y=p(h);g.beginPath();g.moveTo(x.x,x.y);g.lineTo(y.x,y.y);g.stroke()}}
function synth(t){const l=Array.from({length:33},()=>({x:.5,y:.5,visibility:.98})),q=Math.sin(t*2.7)*.04,a=Math.sin(t*5)*.1;l[0]={x:.5+q,y:.1,visibility:.98};l[7]={x:.47+q,y:.12,visibility:.98};l[8]={x:.53+q,y:.12,visibility:.98};for(const[i,x,y]of[[11,.43,.27],[12,.57,.27],[23,.46,.56],[24,.54,.56],[25,.45,.74],[26,.55,.74],[27,.44,.93],[28,.56,.93]])l[i]={x:x+q,y,visibility:.98};l[15]={x:.3,y:.4+a,visibility:.98};l[16]={x:.7,y:.4-a,visibility:.98};return l}
function source(id,t){if(!$('camera'+id+'Enabled').checked)return {};if(state.mode==='sim')return {landmarks:synth(t/1000),receivedAt:t,timestamp:Date.now(),meta:{simulation:true}};const remote=currentRemote(state.remote,id,t);const useRemote=settings()['source'+id]==='remote';if(useRemote)return remote||{};return {landmarks:state.runtime?.landmarks[id]||null,receivedAt:t,timestamp:state.runtime?.timestamps[id],meta:{videoWidth:$('video'+id).videoWidth,videoHeight:$('video'+id).videoHeight}}}
function chart(){drawPhaseChart($('phaseChart'),state.trial.phaseHistory)}
function feedback(phase,m){const s=settings(),visible=s.when==='concurrent'&&state.trial.recording&&phase.valid;const shown=s.when==='terminal'&&!state.trial.recording&&Number.isFinite(state.terminalPhase)?{valid:true,value:state.terminalPhase}:phase;renderPhaseGauge({valueElement:$('phaseValue'),needleElement:$('phaseNeedle'),phase:shown});$('feedbackTitle').textContent=s.what==='kr'?'結果（相対位相）':'過程（左右手の協調）';$('detail').textContent=s.amount==='detailed'&&visible?`目標 ${s.target}° / 誤差 ${wrapDegrees(phase.value-s.target).toFixed(1)}° / 信頼性 ${(m.confidence??0).toFixed(2)}`:'';if(visible)message(Math.abs(wrapDegrees(phase.value-s.target))<=s.tolerance?'目標範囲内':'目標範囲外');for(const conn of Object.values(state.connections))if(conn?.open)conn.send({type:'feedback',visible,value:phase.value,target:s.target,tolerance:s.tolerance,what:s.what,amount:s.amount,how:s.how})}
function frame(t){if(!state.looping)return;const inputs={A:source('A',t),B:source('B',t)},measures={};for(const id of['A','B']){draw(id,inputs[id].landmarks,inputs[id].meta);measures[id]=measurePose(inputs[id].landmarks,state.previous[id],t);if(!measures[id].missing)state.previous[id]=measures[id];$('readout'+id).textContent=$('camera'+id+'Enabled').checked?(inputs[id].landmarks?'検出':'未検出'):'無効';}
 const m=measures.A.missing?measures.B:measures.A;state.phaseWindow.push({time:t,left:m.leftWristY,right:m.rightWristY});if(state.phaseWindow.length>180)state.phaseWindow.shift();const phase=relativePhase(state.phaseWindow);$('trunkValue').textContent=m.bodyAxisHead==null?'—':m.bodyAxisHead.toFixed(1)+'°';$('kneeValue').textContent=measures.B.leftKnee==null?'—':measures.B.leftKnee.toFixed(1)+'°';$('confValue').textContent=m.confidence==null?'—':m.confidence.toFixed(2);$('syncValue').textContent=inputs.A.timestamp&&inputs.B.timestamp?Math.abs(inputs.A.timestamp-inputs.B.timestamp)+' ms':'—';
 const displaySample={monotonicTime:t,leftWristY:m.leftWristY,rightWristY:m.rightWristY,relativePhase:phase.valid?phase.value:null};appendPhaseHistory(state.trial,displaySample);
 if(state.trial.recording){const s=settings();appendTrialSample(state.trial,{sessionId,trial:$('trial').value,condition:$('condition').value,memo:$('memo').value,wallTime:nowIso(),monotonicTime:t,mode:state.mode,sourceA:s.sourceA,sourceB:s.sourceB,cameraA:inputs.A.meta,cameraB:inputs.B.meta,...m,relativePhase:phase.valid?phase.value:null,phaseReason:phase.valid?'':phase.reason,missingA:measures.A.missing,missingB:measures.B.missing,freshnessA:inputs.A.receivedAt?t-inputs.A.receivedAt:null,freshnessB:inputs.B.receivedAt?t-inputs.B.receivedAt:null,timeDifference:inputs.A.timestamp&&inputs.B.timestamp?inputs.A.timestamp-inputs.B.timestamp:null,bf:s})}
 feedback(phase,m);if(t%100<18)chart();requestAnimationFrame(frame)}
function ensureLoop(){if(!state.looping){state.looping=true;requestAnimationFrame(frame)}}
function stopInputs(){state.runtime?.stop();state.runtime=null;state.looping=false;for(const id of['A','B'])draw(id,null)}
async function startCams(){stopInputs();state.mode='camera';state.runtime=new CameraRuntime({onState:(id,text)=>{$(id.toLowerCase()+'State').textContent=text},onError:message,onFrame:(id,lm)=>{if(!lm)draw(id,null)}});if(await state.runtime.start({A:$('cameraAEnabled').checked,B:$('cameraBEnabled').checked}))ensureLoop()}
function startSim(){stopInputs();state.mode='sim';$('simulationBadge').hidden=false;message('SIMULATION：模擬データは実測値ではありません');ensureLoop()}
function startTrial(){state.terminalPhase=null;state.phaseWindow=[];beginTrial(state.trial,nowIso());$('modeStatus').textContent='計測中';ensureLoop();message('新しい試行を開始しました')}
function stopTrial(){endTrial(state.trial);$('modeStatus').textContent='停止';if(settings().when==='terminal'){$('feedback').hidden=false;const valid=state.trial.samples.filter(x=>Number.isFinite(x.relativePhase));const mean=circularMeanDegrees(valid.map(x=>x.relativePhase));state.terminalPhase=mean;$('phaseValue').textContent=mean==null?'算出不能':mean.toFixed(1)+'°';message(`Terminal KR：試行 ${$('trial').value} / 有効 ${valid.length} samples`)}}
function reset(){state.terminalPhase=null;resetTrialState(state.trial);state.phaseWindow=[];state.previous={A:null,B:null};$('phaseValue').textContent='—';chart();message('試行データをリセットしました')}
function download(kind){const meta={sessionId,trialStarted:state.trial.trialStarted,exportedAt:nowIso(),settings:settings(),samples:state.trial.samples};let body,type;if(kind==='json'){body=JSON.stringify(meta,null,2);type='application/json'}else{const flat=state.trial.samples.map(x=>({...x,cameraA:JSON.stringify(x.cameraA),cameraB:JSON.stringify(x.cameraB),bf:JSON.stringify(x.bf)})),keys=[...new Set(flat.flatMap(Object.keys))];body='\ufeff'+keys.join(',')+'\n'+flat.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(',')).join('\n');type='text/csv'}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=`slackline-${sessionId}-${$('trial').value}.${kind}`;a.click();URL.revokeObjectURL(a.href)}
function updateCameraControls(){for(const id of['A','B']){const enabled=$('camera'+id+'Enabled').checked;document.querySelector(`[data-view="${id==='A'?'front':'side'}"]`).classList.toggle('camera-disabled',!enabled);$('readout'+id).textContent=enabled?'待機':'無効';if(!enabled)draw(id,null)}message($('cameraAEnabled').checked||$('cameraBEnabled').checked?'有効なカメラの入力を待っています':'カメラA/Bが無効です')}
for(const id of['A','B'])$('camera'+id+'Enabled').onchange=updateCameraControls;updateCameraControls();
$('startCams').onclick=startCams;$('stopAll').onclick=stopInputs;$('startSim').onclick=startSim;$('startTrial').onclick=startTrial;$('stopTrial').onclick=stopTrial;$('resetTrial').onclick=reset;$('downloadCsv').onclick=()=>download('csv');$('downloadJson').onclick=()=>download('json');$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();$('liveVideo').onchange=e=>document.querySelectorAll('video').forEach(v=>v.style.visibility=e.target.value==='on'?'visible':'hidden');$('how').onchange=()=>ensureLoop();
window.addEventListener('error',e=>message('JavaScriptエラー: '+e.message));window.addEventListener('unhandledrejection',e=>message('非同期エラー: '+e.reason));
async function setupRemote(){try{const{default:Peer}=await import('https://cdn.jsdelivr.net/npm/peerjs@1.5.5/+esm');const peer=new Peer();peer.on('open',id=>{ $('roomCode').textContent=`ROOM ${id.slice(-6).toUpperCase()}`;for(const slot of['A','B']){const u=new URL('./capture.html',location.href);u.searchParams.set('peer',id);u.searchParams.set('source',slot);$('link'+slot).href=u.href;const q=$('qr'+slot);q.replaceChildren();if(window.QRCode)new QRCode(q,{text:u.href,width:160,height:160})}});peer.on('call',call=>{const slot=call.metadata?.source==='B'?'B':'A';call.answer(new MediaStream());call.on('stream',s=>{const v=$('video'+slot);v.srcObject=s;v.play().catch(()=>{});$('state'+slot).textContent='映像受信中'});call.on('close',()=>{$('state'+slot).textContent='映像切断';const v=$('video'+slot);v.srcObject=null})});peer.on('connection',conn=>{const slot=conn.metadata?.source==='B'?'B':'A';state.connections[slot]=conn;conn.on('data',d=>{if(d.type!=='pose')return;storeRemote(state.remote,slot,d,performance.now());$('state'+slot).textContent=d.landmarks?'映像・ランドマーク受信中':'映像あり・未検出';ensureLoop()});conn.on('close',()=>{delete state.connections[slot];delete state.remote[slot];$('state'+slot).textContent='ランドマーク受信停止';draw(slot,null)})})}catch(e){message('PeerJS接続失敗: '+e.message)}}setupRemote();
