const MP_VERSION='0.10.35';
const MP_URL=`https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${MP_VERSION}`;
const WASM_URL=`${MP_URL}/wasm`;
const MODEL_URL='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/1/pose_landmarker_full.task';
export class CameraRuntime{
 constructor({onState=()=>{},onError=()=>{},onFrame=()=>{},onVideo=()=>{}}={}){this.onState=onState;this.onError=onError;this.onFrame=onFrame;this.onVideo=onVideo;this.pose=null;this.streams={A:null,B:null};this.landmarks={A:null,B:null};this.timestamps={A:null,B:null};this.videos={A:document.getElementById('videoA'),B:document.getElementById('videoB')};this.raf=0;this.running=false;this.generation=0;this.devices=[]}
 async init(){if(this.pose)return true;this.onError(`Loading MediaPipe ${MP_VERSION}…`);try{const{FilesetResolver,PoseLandmarker}=await import(MP_URL);this.onError(`Loading MediaPipe WASM ${MP_VERSION}…`);const f=await FilesetResolver.forVisionTasks(WASM_URL);this.onError('Initializing Pose Landmarker…');this.pose=await PoseLandmarker.createFromOptions(f,{baseOptions:{modelAssetPath:MODEL_URL},runningMode:'VIDEO',numPoses:1,outputSegmentationMasks:true});this.onError(`MediaPipe ${MP_VERSION} ready`);return true}catch(e){this.pose=null;this.onError(`MediaPipe initialization failed: ${e.message}`);return false}}
 async enumerate(){this.devices=(await navigator.mediaDevices?.enumerateDevices?.()||[]).filter(d=>d.kind==='videoinput');return this.devices}
 async open(id,deviceId=''){if(this.streams[id])return true;const video=this.videos[id];if(!video)throw Error(`video element missing: ${id}`);try{const c={video:deviceId?{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}}:{width:{ideal:1280},height:{ideal:720}},audio:false};const stream=await navigator.mediaDevices.getUserMedia(c);const actual=stream.getVideoTracks()[0]?.getSettings?.().deviceId;const aid=this.streams.A?.getVideoTracks?.()[0]?.getSettings?.().deviceId;if(id==='B'&&actual&&aid===actual){stream.getTracks().forEach(t=>t.stop());this.onState('B','Not connected (same PC camera as Camera 1)');return false}this.streams[id]=stream;video.srcObject=stream;await video.play().catch(()=>{});this.onVideo(id,true);this.onState(id,'Connected');return true}catch(e){const m=e.name==='NotAllowedError'?'Permission denied':e.name==='NotFoundError'?'Camera not found':e.name==='NotReadableError'?'Camera is in use by another application':`Connection failed: ${e.message}`;this.onState(id,m);return false}}
 async start(enabled={A:true,B:true}){this.onError('Starting cameras…');if(!(await this.init()))return false;this.onError('Requesting camera permission…');await this.enumerate();const a=enabled.A?await this.open('A'):false;if(!enabled.A)this.onState('A','Input disabled');let b=false;await this.enumerate();if(enabled.B&&(this.devices.length>1||!a)&&this.devices.length){const aid=this.streams.A?.getVideoTracks?.()[0]?.getSettings?.().deviceId;const other=this.devices.find(d=>d.deviceId!==aid);b=await this.open('B',other?.deviceId||'')}else this.onState('B',!enabled.B?'Input disabled':this.devices.length<=1?'Not connected (only one camera found)':'Not connected');this.running=a||b;this.generation++;if(this.running)this.loop(this.generation);return this.running}
 loop(g){if(!this.running||g!==this.generation)return;const now=performance.now();for(const id of ['A','B']){const v=this.videos[id];if(!this.streams[id]||v.readyState<2)continue;try{const r=this.pose.detectForVideo(v,now);const lm=r.landmarks?.[0]||null;this.landmarks[id]=lm;this.masks??={};this.masks[id]?.close?.();this.masks[id]=r.segmentationMasks?.[0]||null;this.timestamps[id]=lm?Date.now():null;this.onState(id,lm?`Tracking ${lm.length} landmarks / ${v.videoWidth}x${v.videoHeight}`:`Video available / no pose detected`);this.onFrame(id,lm,this.timestamps[id],this.masks[id])}catch(e){this.landmarks[id]=null;this.timestamps[id]=null;this.onError(`Pose estimation error (${id}): ${e.message}`);this.onState(id,'Estimation error');this.onFrame(id,null,null,null)}}this.raf=requestAnimationFrame(()=>this.loop(g))}
 stop(){this.running=false;this.generation++;cancelAnimationFrame(this.raf);for(const id of ['A','B']){this.streams[id]?.getTracks().forEach(t=>t.stop());this.streams[id]=null;this.landmarks[id]=null;this.masks?.[id]?.close?.();if(this.masks)this.masks[id]=null;this.timestamps[id]=null;if(this.videos[id])this.videos[id].srcObject=null;this.onVideo(id,false);this.onState(id,'Stopped')}}
}
