export class CameraRuntime {
  constructor({onState,onError}={}){this.onState=onState||(()=>{});this.onError=onError||(()=>{});this.pose=null;this.streams={A:null,B:null};this.video={A:document.getElementById('videoA'),B:document.getElementById('videoB')};this.lm={A:null,B:null};this.running=false;this.raf=0}
  async init(){if(this.pose)return true;this.onError('MediaPipe初期化中…');try{const {FilesetResolver,PoseLandmarker}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22');const v=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');this.pose=await PoseLandmarker.createFromOptions(v,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/1/pose_landmarker_full.task'},runningMode:'VIDEO',numPoses:1});this.onError('MediaPipe初期化済み');return true}catch(e){this.onError('MediaPipe読込失敗: '+e.message);return false}}
  async open(id){if(this.streams[id])return true;const v=this.video[id];if(!v)throw Error('video element missing: '+id);try{this.streams[id]=await navigator.mediaDevices.getUserMedia({video:true,audio:false});v.srcObject=this.streams[id];this.onState(id,'接続中');return true}catch(e){this.onState(id,e.name==='NotFoundError'?'カメラ未検出':e.name==='NotAllowedError'?'権限拒否':e.name==='NotReadableError'?'他アプリが使用中':'接続失敗');return false}}
  async start(){if(!(await this.init()))return false;const a=await this.open('A');const b=await this.open('B');this.running=a||b;if(this.running)this.loop();return this.running}
  loop(){if(!this.running)return;const t=performance.now();for(const id of ['A','B']){const v=this.video[id];if(this.streams[id]&&v.readyState>=2){try{this.lm[id]=this.pose.detectForVideo(v,t).landmarks?.[0]||null}catch(e){this.onError('姿勢推定エラー: '+e.message)}}}this.raf=requestAnimationFrame(()=>this.loop())}
  landmarks(id){return this.lm[id]||null}
  stop(){this.running=false;cancelAnimationFrame(this.raf);for(const id of ['A','B']){this.streams[id]?.getTracks().forEach(t=>t.stop());this.streams[id]=null;this.lm[id]=null;this.onState(id,'停止')}}
}
