import assert from 'node:assert/strict';
import { gaugePercent, normalizeHow, participantState } from './feedback-state.mjs';
assert.deepEqual(normalizeHow(['numeric','waveform','gauge']),['numeric','waveform','gauge']);
assert.deepEqual(normalizeHow(['waveform','gauge']),['waveform','gauge']);
assert.deepEqual([-180,-90,0,90,180].map(gaugePercent),[0,25,50,75,100]); assert.equal(gaugePercent(Number.NaN),null);
const base={when:'none',what:'kr',amount:'simple',how:['numeric','waveform','gauge'],target:0,tolerance:20,cameraImageEnabled:true};
assert.equal(participantState(base,true,null,{valid:true,value:20}).visible,false);
assert.equal(participantState({...base,when:'concurrent'},true,null,{valid:true,value:20}).visible,true);
assert.equal(participantState({...base,when:'terminal'},true,30,{valid:true,value:20}).visible,false);
assert.equal(participantState({...base,when:'terminal'},false,30,{valid:false}).visible,true);
assert.equal(participantState({...base,cameraImageEnabled:false},true,null,{valid:true,value:20}).cameraImageEnabled,false);
console.log('feedback state tests passed: multi-HOW, gauge mapping, WHEN, camera and terminal state');
