import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8'), app=fs.readFileSync('app.js','utf8'), runtime=fs.readFileSync('camera-runtime.js','utf8');
const feedbackHtml=fs.readFileSync('feedback.html','utf8'), feedbackApp=fs.readFileSync('feedback.js','utf8');
const capture=fs.readFileSync('capture.js','utf8'), remotePose=fs.readFileSync('src/pose.js','utf8');
const ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]));
const referenced=[...app.matchAll(/\$\('([^']+)'\)/g)].map(x=>x[1]);
assert.deepEqual([...new Set(referenced.filter(id=>!ids.has(id)))],[], 'app.js references a missing DOM id');
for(const camera of ['A','B']) for(const control of ['Video','Reference','Axis','Skeleton','Joints']) assert(ids.has(`camera${camera}${control}`));
for(const id of ['cameraAEnabled','cameraBEnabled','phaseGauge','phaseTarget','phaseTolerance','phaseChart']) assert(ids.has(id));
assert.match(app,/cameraPhaseObservation\(time, measures\.A\)/, 'phase must use camera A only');
assert.doesNotMatch(app,/measures\.A\.missing\s*\?\s*measures\.B/, 'phase must not fall back to B');
assert.match(app,/state\.remoteStreams\[slot\]=stream; bindVideoSources\(\)/, 'remote video must be routed to the selected camera slot');
assert.match(runtime,/this\.onVideo\(id,true\)/, 'local video playback must clear waiting state');
assert.match(app,/terminalResult = result \?\? Number\.NaN/, 'terminal result must persist, including unavailable result');
assert.match(app,/circularMeanDegrees\(valid\)/, 'terminal result must use circular mean');
assert(html.indexOf('phase-monitor') < html.indexOf('experiment panel'), 'research monitor must precede settings');
assert.match(html,/id="how"[\s\S]*type="checkbox"/, 'HOW must use checkboxes');
assert.match(app,/new BroadcastChannel\('slackline-feedback-v1'\)/); assert.match(feedbackApp,/BroadcastChannel\('slackline-feedback-v1'\)/);
assert.match(feedbackHtml,/id="cameraWrap"/); assert.match(app,/rawLeftWristY/); assert.match(app,/filteredLeftWristY/);
assert.match(app,/landmarks\.slice\(11\)/, 'face landmarks 0-10 must not be drawn as joint markers');
assert.match(capture,/l\.slice\(11\)/, 'legacy capture preview must suppress face landmarks');
assert.match(remotePose,/if\(i<11/, 'remote capture preview must suppress face landmarks');
assert.match(remotePose,/if\(start<11\|\|end<11\)/, 'remote capture connections must suppress face landmarks');
for(const id of ['yAxisMode','yAutoRange','yMin','yMax','relativeBaseline','graphWarning'])assert(ids.has(id));
for(const source of ['pc','device1','device2'])assert.match(html,new RegExp(`option value="${source}"`));
for(const camera of ['A','B'])for(const setting of ['backgroundMode','backgroundBlur','backgroundColor'])assert(ids.has(`${setting}${camera}`));
assert.match(app,/Choose another source for either camera/, 'duplicate PC camera choice must warn instead of silently changing the selection');
for(const file of ['index.html','capture.html','feedback.html'])assert.doesNotMatch(fs.readFileSync(file,'utf8'),/[ぁ-んァ-ン一-龯]/,`${file} must contain English UI text only`);
console.log('integration tests passed: DOM ids, camera controls, video presence, A-only phase, terminal persistence');
