const MP_VERSION='0.10.35';
const MP_URL=`https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${MP_VERSION}`;
const WASM_URL=`${MP_URL}/wasm`;
const MODEL_URL='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/1/pose_landmarker_full.task';
export class CameraRuntime{
 constructor({onState=()=>{},onError=()=>{},onFrame=()=>{}}={}){this.onState=onState;this.onError=onError;this.onFrame=onFrame;this.pose=null;this.streams={A:null,B:null};this.landmarks={A:null,B:null};this.timestamps={A:null,B:null};this.videos={A:document.getElementById('videoA'),B:document.getElementById('videoB')};this.raf=0;this.running=false;this.generation=0;this.devices=[]}
 async init(){if(this.pose)return true;this.onError(`MediaPipe ${MP_VERSION} 読込中…`);try{const{FilesetResolver,PoseLandmarker}=await import(MP_URL);this.onError(`MediaPipe WASM ${MP_VERSION} 読込中…`);const f=await FilesetResolver.forVisionTasks(WASM_URL);this.onError('PoseLandmarkerモデル初期化中…');this.pose=await PoseLandmarker.createFromOptions(f,{baseOptions:{modelAssetPath:MODEL_URL},runningMode:'VIDEO',numPoses:1});this.onError(`MediaPipe ${MP_VERSION} 初期化済み`);return true}catch(e){this.pose=null;this.onError(`MediaPipe初期化失敗: ${e.message}`);return false}}
 async enumerate(){this.devices=(await navigator.mediaDevices?.enumerateDevices?.()||[]).filter(d=>d.kind==='videoinput');return this.devices}
 async open(id,deviceId=''){if(this.streams[id])return true;const video=this.videos[id];if(!video)throw Error(`video element missing: ${id}`);try{const c={video:deviceId?{deviceId:{exact:deviceId},width:{ideal:1280},height:{ideal:720}}:{width:{ideal:1280},height:{ideal:720}},audio:false};const stream=await navigator.mediaDevices.getUserMedia(c);const actual=stream.getVideoTracks()[0]?.getSettings?.().deviceId;const aid=this.streams.A?.getVideoTracks?.()[0]?.getSettings?.().deviceId;if(id==='B'&&actual&&aid===actual){stream.getTracks().forEach(t=>t.stop());this.onState('B','未接続（Aと同じカメラ）');return false}this.streams[id]=stream;video.srcObject=stream;await video.play().catch(()=>{});this.onState(id,'接続中');return true}catch(e){const m=e.name==='NotAllowedError'?'権限拒否':e.name==='NotFoundError'?'カメラ未検出':e.name==='NotReadableError'?'他アプリが使用中':`接続失敗: ${e.message}`;this.onState(id,m);return false}}
 async start(){this.onError('カメラ開始: 初期化中…');if(!(await this.init()))return false;this.onError('カメラ権限取得中…');await this.enumerate();const a=await this.open('A');let b=false;await this.enumerate();if(a&&this.devices.length>1){const aid=this.streams.A?.getVideoTracks?.()[0]?.getSettings?.().deviceId;const other=this.devices.find(d=>d.deviceId!==aid);b=await this.open('B',other?.deviceId||'')}else this.onState('B',this.devices.length<=1?'未接続（カメラ1台）':'未接続');this.running=a||b;this.generation++;if(this.running)this.loop(this.generation);return this.running}
 loop(g){if(!this.running||g!==this.generation)return;const now=performance.now();for(const id of ['A','B']){const v=this.videos[id];if(!this.streams[id]||v.readyState<2)continue;try{const r=this.pose.detectForVideo(v,now);const lm=r.landmarks?.[0]||null;this.landmarks[id]=lm;this.timestamps[id]=lm?Date.now():null;this.onState(id,lm?`推定中: ${lm.length}点 / video ${v.videoWidth}x${v.videoHeight}`:`映像あり・未検出`);this.onFrame(id,lm,this.timestamps[id])}catch(e){this.landmarks[id]=null;this.timestamps[id]=null;this.onError(`姿勢推定エラー(${id}): ${e.message}`);this.onState(id,'推定エラー');this.onFrame(id,null,null)}}this.raf=requestAnimationFrame(()=>this.loop(g))}
 stop(){this.running=false;this.generation++;cancelAnimationFrame(this.raf);for(const id of ['A','B']){this.streams[id]?.getTracks().forEach(t=>t.stop());this.streams[id]=null;this.landmarks[id]=null;this.timestamps[id]=null;if(this.videos[id])this.videos[id].srcObject=null;this.onState(id,'停止')}}
}
